# Copyright 2022 SLSA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: test

permissions:
  contents: read

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ../__TOOL_CHECKOUT_DIR__
      - shell: bash
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE/__PROJECT_CHECKOUT_DIR__" >> $GITHUB_ENV
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

          #mkdir -p some/actions/
          mv ../__TOOL_CHECKOUT_DIR__/actions/build-artifacts-composite/* ../some/actions/

      - name: Checkout the project repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false
          #path: __PROJECT_CHECKOUT_DIR__

      # - shell: bash
      #   run: |
      #     ls ./__PROJECT_CHECKOUT_DIR__/
      #     mv ./__PROJECT_CHECKOUT_DIR__/* .

      - uses: ./../some/actions
        env:
          SLSA_SECRETS: some-secrets
      # - uses: ./actions/build-artifacts-composite
      #   env:
      #     SLSA_SECRETS: some-secrets
